<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\GalaxyMonitor.Core\GalaxyMonitor.Core.csproj" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.4" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1" />
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>
</Project>
